<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>EDV.Framework.Core</RootNamespace>
        <AssemblyName>EDV.Framework.Core</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mediator.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

</Project>
